### PR TITLE
Feature/fix wsc parse args

### PR DESCRIPTION
**Pull request by pinin4fjords**
This PR fixes wsc_parse_args to work as it's intended. I hadn't appreciated that where 'NULL' is the default value, optparse doesn't even add a value to its array, so you have to check that the field is there (default NULL)  before you can check if it's NA.

### CODE REVIEW

**Comment by nh3** [comment]
Well, perhaps optparse is doing what it is expected to do: assign `NULL` to `opt$opt_name`. Just that for any R list, assigning `NULL` to its member is effectively removing that member from the list.

```
> x <- list(a=1)
> x$a <- NULL
> x
named list()
```

Perhaps it makes sense to set default value for all mandatory options to `NULL` (or `NA`), so you only need check for one of them.

**Review by nh3 — APPROVED** [review]

**Comment by pinin4fjords** [comment]
Thanks @nh3 - good points. I think this will work for now

**Comment by nh3** [comment]
Yes this will work for now. But, the check for `NA` is probably unnecessary and encouraging inappropriate setting of `default` in `make_option()`. If someone set `default` to a non-NA value, then your tests won't tell if the option is supplied by the user or not. Philosophically, there really shouldn't be default values for mandatory options. Without setting `default`, it defaults to `NULL` and will be caught by your first check.

**Comment by pinin4fjords** [comment]
Thanks @nh3 . I'm not quite sure what you're getting at. The change here will just make the script die if a mandatory argument is either missing or set to NA. If the default is set to a non-NA non-NULL value then all's good and things continue. What's the issue?

We have quite a few places where we use NA and NULL for defaults (in an attempt to mirror function defaults, probably because I'd failed to notice the NULL setting thing you mentioned), so we need to be able to account for them at least for the moment.

**Comment by nh3** [comment]
It concerns the meaning of "mandatory". Does it mean that the option needs to be set by the user, or does it simply mean that it must not be NULL or NA?

If it's the former, then default shouldn't be set in make_option() for mandatory options, and you only need to check for NULL. Otherwise, if the default is set to non-NA value, then your test will pass but still unable to tell if the value is set by the user or not.

If it's the latter, I'd be surprised that the corresponding underlying function use NULL or NA as the default value for anything that is considered mandatory. If so, why must they not be NULL or NA? For example, in `dropletutils-read-10x-counts.R`, the current mandatory options are `--samples` and `--output-object-file`, and the underlying functions are: `read10xCounts(samples, col.names=FALSE, ...)` (samples is really mandatory and has no default value) and `saveRDS(object, file = "", ascii = FALSE, version = NULL, compress = TRUE, refhook = NULL)` (file has empty string as default value).

**Comment by pinin4fjords** [comment]
The purpose of the function is simply to check that a set of values is present for the parameters specified under 'mandatory'. I take your point about usage, but it's a separate issue I think.

**Pull request merged**
